name: scheduler-service
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      hubAddressGroupObject:
        type: choice
        description: 'Deploy service 🚀🚀🚀'
        required: true
        default: 'TEST'
        options:
          - 'TEST'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - develop
      - "release/v[0-9]+.[0-9]+.[0-9]+*"
      - "refs/tags/v[0-9]+.[0-9]+.[0-9]+*"
  workflow_call:
  

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.base_ref }}-${{ github.run_id }}

jobs:
  build-dev:
    environment: development
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          
  build-stg:
    environment: staging
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    steps:
      - name: Get branch release
        run: |
          GET_BRANCH_VERSION_RELEASE=$(git ls-remote --heads | awk '{print $2}' | egrep -o "refs/heads/release/v[0-9]+\.[0-9]+\.[0-9]+.?" | grep -Ev '-')
          echo "BRANCH_VERSION_RELEASE=${GET_BRANCH_VERSION_RELEASE#refs/heads/}" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_VERSION_RELEASE }}
          
  build-prod:
    environment: production
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
