name: scheduler-service
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      hubAddressGroupObject:
        type: choice
        description: 'Deploy service 🚀🚀🚀'
        required: true
        default: 'TEST'
        options:
          - 'TEST'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - develop
      - "release/v[0-9]+.[0-9]+.[0-9]+*"
      - "refs/tags/v[0-9]+.[0-9]+.[0-9]+*"
  workflow_call:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          
  build-stg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop
          
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
