name: Build test

on:
  # release:
  #  types:
  #    - created
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - refs/tags/*
      - release/*
      - hotfix/*
      - develop
      - main
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - main
      - refs/tags/*
      - hotfix/*
      - release/*
      - develop

env:
  NAME_SERVICE: service_a
  IMAGE_TAG_LATEST: latest
  DOCKER_BUILDKIT: 1
  DEPLOYMENTS: true

concurrency:
  group: ${{ github.ref }}-${{ github.run_id }}

jobs:
  build-dev:
    if: startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pre-check step and set env
        run: echo "${GITHUB_REF#refs/tags/}, test ${GITHUB_REF}"

      - name: Pre-check step and set env dev
        id: get_current_env_dev
        if: ${{ github.event.ref == 'refs/heads/develop' }}
        run: |
          if [[ ${{ github.event.ref }} == 'refs/heads/develop' ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
            echo "CURRENT_ENV=dev" >> "$GITHUB_ENV"
            echo "PROJECT_FOLDER=${GITHUB_REPOSITORY#onpointvn/}" >> "$GITHUB_ENV"
            echo "[INFO] PASSED pre-check. Using build automatically"
            echo "[INFO] PASSED pre-check. Using build automatically"
            exit 0
          fi

      - name: Get Tag Name
        run: echo "VERSION ${{ env.VERSION }} - $GITHUB_REF_NAME"
      - name: Get Target Name Branch
        run: echo "Get Target Name Branch ${{ github.event.release.target_commitish }}"

  deploy-dev:
    if: startsWith(github.ref, 'refs/heads/develop')
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pre-check step and set env
        run: echo "${GITHUB_REF#refs/tags/}, test ${GITHUB_REF}"

      - name: Build, tag and push image to Amazon ECR
        run: |
          IMAGE_VERSION=$(echo ${{ github.sha }} | cut -c1-9)
          ECR_REPOSITORY="${NAME_SERVICE}_${CURRENT_ENV}"
          AWS_ECR_DOCKER_IMAGE="${AWS_K8S_CONTAINER_NAME}:${IMAGE_VERSION}"


      - name: Get Tag Name
        run: echo "VERSION ${{ env.VERSION }} - $GITHUB_REF_NAME"
        
      - name: Get Tag Name IMAGE_VERSION
        run: echo "IMAGE_VERSION ${{ env.IMAGE_VERSION }} - $IMAGE_VERSION"

      
      - name: Get Target Name Branch
        run: echo "Get Target Name Branch ${{ github.event.release.target_commitish }}"
